### ISSUE TITLE
Thanks for your node!

### ISSUE THREAD

**Issue by T8star1984** [frankchieng/ComfyUI_Aniportrait#2]
I test this node,the effect is good than I expect.I'm looking forward to support but only 512*512 not also other resolution ratio

**Comment by frankchieng** [comment]
> I test this node,the effect is good than I expect.I'm looking forward to support but only 512*512 not also other resolution ratio

yep,i just refactor the original project yet,i will add all kinds of params in the node later,like cfg width height fps etc

**Comment by frankchieng** [comment]
> I test this node,the effect is good than I expect.I'm looking forward to support but only 512*512 not also other resolution ratio

i've update the nodes and add corresponding parameters
